### ISSUE TITLE
Save temporary files only

### ISSUE THREAD

**Issue by tischi** [ilastik/ilastik4ij#27]
@wolny @k-dominik 
I do not understand why one needs this:
```
    @Parameter(label = "Save temporary file for training only, without prediction.")
    private Boolean saveOnly = false;
```
Do you know?

**Comment by k-dominik** [comment]
Hey @tischi, the reason this functionality is there is convenience for the user, obviously not communicated clearly.
For ilastik we require the data that we use in predictions to have the same axes as the data in training. Since we might misinterpret axes from whatever tif the users might want to use, we prefer to save the image to hdf5, with axistags that we understand. So the problem is that we would need to export the image to hdf5 using the ilastik plugin _before_ training to have it in 5D with no ambiguities about the axes.
So, having this checkbox here is a shorthand to export the file to hdf5, in a temporary folder, just for training.

Do you think that's too convoluted?

**Comment by wolny** [comment]
Yeah we agreed with @tischi  that it's too convoluted indeed and removed the flag. We'll solve the axis order validation in a different way, i.e. reading it from ilastik's project file and checking if the input conforms with that
