### ISSUE TITLE
Drag and drop support for the hdf5 import

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik4ij#71]
Seems like you cannot drag and drop a file from the file browser (tested on linux) onto the text field of the hdf5 import gui. Would be great to support this.

**Comment by imagejan** [comment]
The SciJava File input widget supports drag-and-drop functionality. It was implemented here:

https://github.com/scijava/scijava-ui-swing/commit/f0d2a878e5881ec4cf2c1de8f8484a7f0771c117

Instead of re-implementing the same in [`IlastikImportDialog`](https://github.com/ilastik/ilastik4ij/blob/95473a567c0f03e24b076e964484d4f043596693/src/main/java/org/ilastik/ilastik4ij/ui/IlastikImportDialog.java), I'd suggest sticking to the standard ways to harvest input provided by the framework. It will reduce the maintenance burden for this project.

**Comment by m-novikov** [comment]
In our case, it's more convenient to have the DnD function on the whole dialog to avoid pixel hunting input field. 
We already use a custom file input widget because we needed to properly align fields on the grid and to be able to connect it to the data model.
In the future, we would like to display recent ilastik projects in this widget.

**Comment by k-dominik** [comment]
> The SciJava File input widget supports drag-and-drop functionality. It was implemented here:
> 
> [scijava/scijava-ui-swing@f0d2a87](https://github.com/scijava/scijava-ui-swing/commit/f0d2a878e5881ec4cf2c1de8f8484a7f0771c117)
> 
> Instead of re-implementing the same in [`IlastikImportDialog`](https://github.com/ilastik/ilastik4ij/blob/95473a567c0f03e24b076e964484d4f043596693/src/main/java/org/ilastik/ilastik4ij/ui/IlastikImportDialog.java), I'd suggest sticking to the standard ways to harvest input provided by the framework. It will reduce the maintenance burden for this project.

Hi @imagejan, I'm always so happy to see your comments here :+1: 

But indeed, the custom widget add _a lot_ of convenience to the dialog. I wouldn't really want to go back!

**Comment by imagejan** [comment]
@k-dominik wrote:

> the custom widget add a lot of convenience to the dialog. I wouldn't really want to go back!

Fair enough, I do understand your reasons. I just makes me a little sad to see that the SciJava project didn't have the developer resources to offer what you apparently required for this project. And to see that the `Command`s in this repository are focused on usage in ImageJ/Fiji and probably won't work in KNIME as they are now, will they?

**Comment by m-novikov** [comment]
> And to see that the Commands in this repository are focused on usage in ImageJ/Fiji and probably won't work in KNIME as they are now, will they?

I was not aware that KNIME also uses SciJava commands. Could you provide an example so maybe we can adapt commands to work in both environments?

> It just makes me a little sad to see that the SciJava project didn't have the developer resources to offer what you apparently required for this project.

There is always a possibility that once we have something working well enough we contribute it to scijava. But it would be a major problem if we didn't test custom forms with our users first to figure out how useful it is in reality.

**Comment by imagejan** [comment]
> Could you provide an example so maybe we can adapt commands to work in both environments?

The first versions of `ilastik4ij` worked in KNIME and were even deployed for a short time, but as far as I can tell, development dried up because of some issues (I am not sure about the details... the ilastik executable needed to be defined as a node parameter, instead of some central config?), and it finally never officially replaced the current custom ilastik integration in KNIME.

Regarding some examples of IJ2/SciJava plugins that *are actually used* in KNIME "in production", see all the commands in this folder:

https://github.com/fmi-faim/fmi-ij2-plugins/tree/f9247a147a3c92d98b15e6af1ee4d34a082cd297/src/main/java/ch/fmi

Disclaimer 1: I am the author of those.
Disclaimer 2: Many of those commands actually just "wrap" ImageJ1 plugins to make them accessible in KNIME.
